from __future__ import annotations

import io
import json
import os
import subprocess
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path

from chengyulang import (
    分析并翻译,
    编译文件,
    编译源码,
    词库加载,
)


class CompilerTests(unittest.TestCase):
    def test_structured_translation_reports_hits(self) -> None:
        结果 = 分析并翻译("值 = 色令智昏(True)\n列(值)")
        self.assertEqual(结果.成语命中列表[0].文本, "色令智昏")
        self.assertEqual(结果.成语命中列表[0].模式, "connected")
        self.assertEqual(结果.结构命中列表[0].类型, "PRINT")

    def test_compile_source_is_runnable_and_reproducible(self) -> None:
        源码 = "值 = 色令智昏(False)\n列(值)\n"
        甲 = 编译源码(源码, 文件名="demo.cy")
        乙 = 编译源码(源码, 文件名="demo.cy")
        self.assertTrue(甲.成功)
        self.assertEqual(甲.Python源码, 乙.Python源码)
        self.assertIn("Generated by ChengyuLang 0.2.0", 甲.Python源码)

        输出 = io.StringIO()
        with redirect_stdout(输出):
            exec(compile(甲.Python源码, "demo.py", "exec"), {})
        self.assertEqual(输出.getvalue(), "True\n")

    def test_compile_does_not_execute_program(self) -> None:
        结果 = 编译源码('鸡飞狗跳("只编译，不执行")')
        self.assertTrue(结果.成功)

    def test_syntax_error_has_stable_diagnostic(self) -> None:
        结果 = 编译源码("若 True\n    列('漏冒号')", 文件名="bad.cy")
        self.assertFalse(结果.成功)
        self.assertEqual(结果.诊断信息[0].代码, "CY1002")
        self.assertEqual(结果.诊断信息[0].行号, 1)
        self.assertIn("句法不通", 结果.诊断信息[0].消息)

    def test_missing_runtime_is_a_semantic_error(self) -> None:
        词典 = 词库加载(
            扩展={
                "纸上谈兵": {
                    "category": "测试",
                    "py": "None",
                    "egg": "纸.上(); 谈兵()",
                    "runtime": "不存在的实现",
                }
            }
        )
        结果 = 编译源码("纸上谈兵()", 词典=词典)
        self.assertFalse(结果.成功)
        self.assertEqual(结果.诊断信息[0].代码, "CY2001")

    def test_compile_file_protects_existing_output(self) -> None:
        with tempfile.TemporaryDirectory() as 临时目录:
            输入 = Path(临时目录, "demo.cy")
            输出 = Path(临时目录, "demo.py")
            输入.write_text("列(色令智昏(False))\n", encoding="utf-8")

            首次 = 编译文件(输入, 输出)
            再次 = 编译文件(输入, 输出)
            覆盖 = 编译文件(输入, 输出, 覆盖=True)

            self.assertTrue(首次.成功 and 首次.已写入)
            self.assertFalse(再次.成功)
            self.assertEqual(再次.诊断信息[-1].代码, "CY3002")
            self.assertTrue(覆盖.成功 and 覆盖.已写入)

    def test_json_catalog_alias_is_embedded(self) -> None:
        词典 = 词库加载(
            扩展={
                "云里雾里": {
                    "category": "测试",
                    "py": "复用不知所云",
                    "egg": "云.里(); 雾.里()",
                    "runtime": "不知所云",
                }
            }
        )
        结果 = 编译源码("列(云里雾里(4))", 词典=词典)
        self.assertTrue(结果.成功)
        self.assertIn("云里雾里", 结果.Python源码)


class CompilerCliTests(unittest.TestCase):
    项目根目录 = Path(__file__).resolve().parents[1]

    def _运行(self, *参数: str) -> subprocess.CompletedProcess[str]:
        环境 = os.environ.copy()
        环境["PYTHONPATH"] = str(self.项目根目录)
        return subprocess.run(
            [sys.executable, "-m", "chengyulang", *参数],
            cwd=self.项目根目录,
            env=环境,
            text=True,
            capture_output=True,
            check=False,
        )

    def test_cli_compiles_then_python_runs_output(self) -> None:
        with tempfile.TemporaryDirectory() as 临时目录:
            输入 = Path(临时目录, "demo.cy")
            输出 = Path(临时目录, "demo.py")
            输入.write_text("列(色令智昏(False))\n", encoding="utf-8")

            编译进程 = self._运行("compile", str(输入), "-o", str(输出))
            self.assertEqual(编译进程.returncode, 0, 编译进程.stderr)
            self.assertTrue(输出.is_file())

            环境 = os.environ.copy()
            环境["PYTHONPATH"] = str(self.项目根目录)
            执行进程 = subprocess.run(
                [sys.executable, str(输出)],
                env=环境,
                text=True,
                capture_output=True,
                check=False,
            )
            self.assertEqual(执行进程.returncode, 0, 执行进程.stderr)
            self.assertEqual(执行进程.stdout, "True\n")

    def test_cli_check_json_is_machine_readable(self) -> None:
        with tempfile.TemporaryDirectory() as 临时目录:
            输入 = Path(临时目录, "demo.cy")
            输入.write_text("列(不知所云(2))\n", encoding="utf-8")
            进程 = self._运行("check", str(输入), "--json")
            self.assertEqual(进程.returncode, 0, 进程.stderr)
            数据 = json.loads(进程.stdout)
            self.assertTrue(数据["success"])
            self.assertEqual(数据["idiom_hits"][0]["text"], "不知所云")
            self.assertFalse(数据["written"])


if __name__ == "__main__":
    unittest.main()

