"""Generate the deterministic runtime prelude for compiled Python files."""

from __future__ import annotations

import hashlib
import json
from typing import Any, Mapping

from .version import __version__


def _安全注释值(文本: str) -> str:
    return " ".join(str(文本).splitlines()) or "<成语语>"


def _规范词库_json(词典: Mapping[str, Mapping[str, Any]]) -> str:
    return json.dumps(
        词典,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    )


def 生成运行时引导(
    源码: str,
    词典: Mapping[str, Mapping[str, Any]],
    *,
    文件名: str = "<成语语>",
) -> str:
    """Return a reproducible prelude for a compiled ChengyuLang program."""

    规范词库 = _规范词库_json(词典)
    源码摘要 = hashlib.sha256(源码.encode("utf-8")).hexdigest()
    词库摘要 = hashlib.sha256(规范词库.encode("utf-8")).hexdigest()
    安全文件名 = _安全注释值(文件名)

    return (
        f"# Generated by ChengyuLang {__version__}\n"
        f"# Source: {安全文件名}\n"
        f"# Source SHA-256: {源码摘要}\n"
        f"# Catalog SHA-256: {词库摘要}\n"
        "# This file requires the chengyulang package at runtime.\n"
        "\n"
        "import json as __chengyu_json__\n"
        "from chengyulang.runtime import (\n"
        "    构建运行环境 as __chengyu_build_runtime__,\n"
        ")\n"
        "\n"
        f"__chengyu_catalog__ = __chengyu_json__.loads({规范词库!r})\n"
        "__chengyu_functions__, __chengyu_egg__ = (\n"
        "    __chengyu_build_runtime__(__chengyu_catalog__)\n"
        ")\n"
        "\n"
        "# ---- ChengyuLang compiled program ----\n"
        "\n"
    )


def 生成Python源码(
    源码: str,
    内部译文: str,
    词典: Mapping[str, Mapping[str, Any]],
    *,
    文件名: str = "<成语语>",
) -> str:
    """Combine the runtime prelude and translated program body."""

    引导 = 生成运行时引导(源码, 词典, 文件名=文件名)
    正文 = 内部译文
    if 正文 and not 正文.endswith("\n"):
        正文 += "\n"
    return 引导 + 正文


# English aliases.
generate_runtime_prelude = 生成运行时引导
generate_python_source = 生成Python源码
